### ISSUE TITLE
Not compat with PHP 5.6

### ISSUE THREAD

**Issue by Eolia** [mailjet/prestashop-mailjet-plugin-apiv3#132]
Hi some corrections are required because static const is not 5.6 compliant
properties functions with : are not compliant too
ternaries with :: idem

**Comment by oleksandr-mykhailenko** [comment]
Hello @Eolia
Thank you, we will check issues with it.

**Comment by tajriba** [comment]
php 5.6 is not safe and outdated.

**Comment by oleksandr-mykhailenko** [comment]
Hello @Eolia This is an really old version of php. We going to update library into modern way. So we recommend to update you php version

**Comment by Pig3onMort** [comment]
My webite is in 1.5.6.2 and I cannot update it to 1.7 because of some custom development and cost reasons. The latest version of PHP accepted on this prestashop version is 5.6. I do understand it is outdated but therefore your module is not compatible with my website, as it is promoted on the mailjet website. I cannot install it for the same reasons as Eolia said.
