### ISSUE TITLE
Changement du serveur SMTP et email boutique

### ISSUE THREAD

**Issue by okom3pom** [mailjet/prestashop-mailjet-plugin-apiv3#65]
Bonjour,

Avant de faire ce PR https://github.com/mailjet/prestashop-mailjet-plugin-apiv3/pull/64

J'ai mis à jour le module d'une 3.2 -> 3.4.last

Je me suis retrouver avec la case  à oui

> Activer l'envoi de tous vos emails avec Mailjet ?  

Déjà pas très cool, bon pas trop grave je la passe à non.
Ensuite changement des serveurs SMTP et changement du mail de la boutique par le mail de connexion au site mailjet ... 

Pas cool surtout quand on se connecte à votre site avec une adresse @free.fr

**Comment by mskochev** [comment]
Hello, the "Shop email" is replaced by the SENDER EMAIL from the Mailjet plugin. This is done, because Prestashop uses the "Shop email" to send its transactional emails.

To avoid the issue that your Shop email is replaced by a @free.fr email, you should add your real email address that you want to use for your shop in your [Mailjet account](https://app.mailjet.com/account/sender) and then select it in the plugin for sending transactional emails.

![image](https://user-images.githubusercontent.com/23452885/51020945-bea91b80-1588-11e9-967c-0aa8d4fca698.png)
